### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Error404-RedRose** [isidorjkaplan/UltraPlugin#1]
I love this plugin and would love to buy it but it needs to be updated to at least 1.17.1 or the new 1.18 coming out soon,
If I were to compile it would it run on 1.17.1?

**Comment by Error404-RedRose** [comment]
also could you maybe compile a quick version of this?

**Comment by Error404-RedRose** [comment]
I will pay for it with paypal if you like

**Comment by isidorjkaplan** [comment]
I mean unless they changed the API it’s based on (which is entirely possible and they have done before) it should just compile and work. Your welcome to attempt to compile it. There are a large number of dependencies though but I think they should be in a folder somewhere here and if they are not then when the plug-in is loaded you should get a missing dependency error that you can look up and include. If you dump any dependency jars into the UltraLib/modules folder it will load them in and maybe run but it’s honestly been years since I maintained this so who knows if it even works anymore
